### PR TITLE
fix: not checking if actors have datasets.

### LINKED ISSUE #208: vtk 9.4.0 fails
Attempted in https://github.com/ansys/pymapdl/pull/3602

The traceback is:

```pytb
/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/ansys/mapdl/core/plotting/visualizer.py:231: AttributeError
____________ Test_plastic_solve.test_plot_nodal_plastic_eqv_strain _____________

mapdl = <ansys.mapdl.core.mapdl_grpc.MapdlGrpc object at 0x7f7c82814910>
resume = None

    @staticmethod
    @requires("ansys-tools-visualization_interface")
    def test_plot_nodal_plastic_eqv_strain(mapdl, resume):
>       assert (
            mapdl.post_processing.plot_nodal_plastic_eqv_strain(smooth_shading=True)
            is None
        )

tests/test_post.py:843: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/ansys/mapdl/core/post.py:3195: in plot_nodal_plastic_eqv_strain
    return self._plot_point_scalars(
/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/ansys/mapdl/core/misc.py:435: in wrapper
    return function(self, *args, **kwargs)
/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/ansys/mapdl/core/post.py:635: in _plot_point_scalars
    return pl.show(**kwargs)
/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/ansys/mapdl/core/plotting/visualizer.py:842: in show
    self._backend.show()
/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/ansys/tools/visualization_interface/backends/pyvista/pyvista.py:436: in show
    self.enable_widgets()
/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/ansys/tools/visualization_interface/backends/pyvista/pyvista.py:186: in enable_widgets
    self._widgets.append(MeshSliderWidget(self))
/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/ansys/tools/visualization_interface/backends/pyvista/widgets/mesh_slider.py:55: in __init__
    self._meshes = self.plotter_helper._pl.scene.meshes
/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pyvista/plotting/plotter.py:7162: in meshes
    return [actor.mapper.dataset for actor in self.actors.values() if hasattr(actor, 'mapper')]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <dict_valueiterator object at 0x7f7c780f4d10>

>   return [actor.mapper.dataset for actor in self.actors.values() if hasattr(actor, 'mapper')]
E   AttributeError: 'NoneType' object has no attribute 'dataset'
```

### PR DESCRIPTION
**Pull request by germa89**
As the title.

Close #208 by implementing our own `meshes` method.

### CODE REVIEW

**Comment by germa89** [comment]
This method wasn't tested, so I leave it up to @AlejandroFernandezLuces if he wants to add a tests or not.

**Review by germa89 — COMMENTED** [review]
The issue has been fixed upstream in https://github.com/pyvista/pyvista/pull/6860.
It is just yet not published.

**Review by germa89 — COMMENTED** [review]
The issue has been fixed upstream in https://github.com/pyvista/pyvista/pull/6860.
It is just yet not published.

**Comment by AlejandroFernandezLuces** [comment]
> This method wasn't tested, so I leave it up to @AlejandroFernandezLuces if he wants to add a tests or not.
> 
> I guess it should not be needed since the slicer (`MeshSliderWidget`) does not seem to be much exposed??

Since this is temporary I think we don't need to test it. Let's merge this if you need it and we can remove it when bumping the next PyVista version.

**Review by AlejandroFernandezLuces — APPROVED** [review]

**Pull request merged**
