### PR TITLE
maint: Upload PDF documentation

### LINKED ISSUE #67: Online docs claim to have PDF available but download fails
I guess we are not uploading the PDF as part of the docs build. This should be automated by https://github.com/ansys/actions/pull/467 but it seems like it has staled.... @SMoraisAnsys what's the status in that PR?

image

We should try and fix it anyway - either wait for the PR to be merged or do it manually.

### PR DESCRIPTION
**Pull request by AlejandroFernandezLuces**
Closes #67

### CODE REVIEW

**Comment by AlejandroFernandezLuces** [comment]
@SMoraisAnsys is this the proper way to upload the PDF in the docs? I'm a bit confused, the PDF is in the appropiate folder when I download the generated HTML documentation, but I still get a 404 when I click the PDF button. Do you mind taking a look?

**Comment by AlejandroFernandezLuces** [comment]
> @SMoraisAnsys is this the proper way to upload the PDF in the docs? I'm a bit confused, the PDF is in the appropiate folder when I download the generated HTML documentation, but I still get a 404 when I click the PDF button. Do you mind taking a look?

Nevermind, it was redirecting me to the actual deployed docs, I think these changes should work. Can you take a look anyway just in case there is any better way to do this?

**Comment by SMoraisAnsys** [comment]
> > @SMoraisAnsys is this the proper way to upload the PDF in the docs? I'm a bit confused, the PDF is in the appropiate folder when I download the generated HTML documentation, but I still get a 404 when I click the PDF button. Do you mind taking a look?
> 
> Nevermind, it was redirecting me to the actual deployed docs, I think these changes should work. Can you take a look anyway just in case there is any better way to do this?

I think you can limit your changes to the workflow input `add-pdf-html-docs-as-assets: true`. The action takes care of  zipping / copying / pasting files to the expected directory `doc/_build/html/_static/assets/download`. If you don't want all PDF files to be copied in the `assets` directory, you might want to be sure that your `project` variable in `conf.py` is `ansys-tools-visualization-interface`. Otherwise every PDF file will get uploaded.

**Comment by AlejandroFernandezLuces** [comment]
Thanks for the feedback 🙂

**Pull request merged**
